
service: authentication
tenant: aengus
app: ski-analytics

provider:
  name: aws
  runtime: java8
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
#  fallback to us-west as cognito not available in canada
  region: us-west-2
  stage: staging
  stackName: ${{self:custom.currentStage}}-ski-analytics-authentication-stack


custom:
  currentStage: ${{opt:stage, self:provider.stage}}

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          InviteMessageTemplate:
            #EmailMessage: ${{file(src/main/resources/verification_email.html)}}
            EmailMessage: "Hello there {username},  You're verification code is {####}"
            EmailSubject: "Welcome to Crunch.Ski!"
          UnusedAccountValidityDays: 365
        AliasAttributes:
            - email
        AutoVerifiedAttributes:
            - email
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: false
          DeviceOnlyRememberedOnUserPrompt: false
#        EmailConfiguration: -> this is erroring out saying invalid email address :(
#          ReplyToEmailAddress: admin@ski-analytics.ca
#          SourceArn: arn:aws:ses:us-west-2:556823078430:identity/ski-analytics.ca
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            RequireUppercase: true
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: false
            Name: email
            Required: true
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: FirstName
            StringAttributeConstraints:
              MinLength: 2
              MaxLength: 20
            Required: false
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: LastName
            StringAttributeConstraints:
              MinLength: 2
              MaxLength: 20
            Required: false
        UserPoolName: ${{self:custom.currentStage}}-crunch-ski-userpool
        UserPoolTags:
          project: ski-analytics
          module: auth

  Outputs:
    UserPoolArn:
      Value:
        Ref: UserPool
    UserPoolProviderName:
      Value:
        Fn::GetAtt: [UserPool, ProviderName]
    UserPoolProviderUrl:
      Value:
        Fn::GetAtt: [UserPool, ProviderURL]