## CircleCI configuration file

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
commands:
  restore-cache:
    steps:
      - restore_cache:  ## Restore gradle cache
          keys:
            - gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-cache-v1-{{ .Branch }}
            - gradle-cache-v1

      - restore_cache:  ## restore node cache
          keys:
           - node-cache-v1
  save-cache:
    steps:
      - save_cache:
          key: gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - save_cache:
          key: node-cache-v1-{{ .Branch }}
          paths:
            - /usr/local/lib/node_modules/

  unit-test:
    steps:
      - run: gradle wrapper --gradle-version 6.2.2 --distribution-type all
      - run: ./gradlew clean
      - run: ./gradlew build --stacktrace
  install-sls:
    steps:
      - node/with-cache:
          steps:
            - run: sudo npm install -g serverless
  install-sls-appsync-plugin:
    steps:
      - run: cd src/graphql && npm install serverless-appsync-plugin && cd ../../
  save-test-results:
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/repo/build/reports/test-results
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/repo/build/reports/test-results/ \;
          when: always
      - store_test_results:
          path: ~/repo/build/reports/test-results
      - store_artifacts:
          path: ~/repo/build/reports/

jobs:
  build:
    docker:
      - image: aengus/crunch-ski:1.0.6
    working_directory: /home/circleci/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore-cache
      - unit-test
      - aws-cli/configure:
          profile-name: backend_dev
      - install-sls-appsync-plugin
      - run: ./gradlew deploy -Dstage="ci" --stacktrace
      - run: ./gradlew clean jacocoRootReport -x cli:integrationTest -Dstage="ci" --stacktrace
      - save-cache
      #- run: ./gradlew jacocoRootReport -x test -x integrationTest
      - run: ./gradlew sendCoverageToCodacy
      - save-test-results
      - store_artifacts:
          path:  ~/repo/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml

workflows:
  version: 2.1
  myworkflow:
    jobs:
      - build:
          context: sls-context

## for provisioning script:
## cd src/graphql &&  npm install serverless-appsync-plugin

## SSM weather and location parameters had disppeared
## need to pass stage parameter to integration test