# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  node: circleci/node@1.1.6

commands:
  restore-cache:
    steps:
      - restore_cache:  ## Restore gradle cache
          keys:
            - gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-cache-v1-{{ .Branch }}
            - gradle-cache-v1

      - restore_cache:  ## restore node cache
          keys:
           - node-cache-v1
  save-cache:
    steps:
      - save_cache:
          key: gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - save_cache:
          key: node-cache-v1-{{ .Branch }}
          paths:
            - /usr/local/lib/node_modules/

  unit-test:
    steps:
      - run: gradle wrapper --gradle-version 6.2 --distribution-type all
      - run: ./gradlew clean
      - run: ./gradlew build
  install-sls:
    steps:
      - node/with-cache:
          steps:
            - run: sudo npm install -g serverless
  save-test-results:
    steps:
      - run:
          name: Save test results
          command: |
            mkdir build/reports/test-results
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} build/reports/test-results/ \;
          when: always
      - store_test_results:
          path: build/reports/test-results
      - store_artifacts:
          path: build/reports/

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/python:3.7-stretch
    executor: aws-cli/default
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore-cache
      - unit-test
      - install-sls
      - aws-cli/install
      - aws-cli/configure:
          profile-name: backend_dev
      - run: ./gradlew deploy -Pstage="ci"
      - run: ./gradlew integrationTest
      - save-cache
      - run: ./gradlew jacocoRootReport
      - run: ./gradlew sendCoverageToCodacy
      - save-test-results
      - store_artifacts:
          path:  build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml

workflows:
  version: 2.1
  myworkflow:
    jobs:
      - build:
          context: sls-context
