

service: layers # NOTE: update this with your service name


provider:
  name: aws
  runtime: java8
  region: ca-central-1
  stage: staging
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
  stackName: ${{self:custom.currentStage}}-ski-analytics-layer-stack

custom:
  currentStage: ${{opt:stage, self:provider.stage}}




layers:
  model:
    name: ${{self:custom.currentStage}}-layer-model
    description: domain classes for object model
    compatibleRuntimes:
      - java8
    path: build/layer
    package:
      include: # Specify the directories and files which should be included in the deployment package
        - src/main/java/ski/crunch/model/*
      artifact: build/distributions/ski-crunch-model.zip


resources:
  Outputs:
    ModelLayerExport:
      Value:
        Ref: ModelLambdaLayer
      Export:
        Name: ModelLambdaLayer