# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: domain-stack
tenant: aengus
app: ski-analytics

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: java8
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
  region: ca-central-1
  stackName: ski-analytics-domain-stack


custom:
  domainName: crunch.ski
  resourceTags:
              -
                Key: "project"
                Value: "ski-analytics"
              -
                Key: "module"
                Value: "domain"

resources:
  Resources:
    HostedZone:
      Type: AWS::Route53::HostedZone
      Properties:
        HostedZoneConfig:
          Comment: "HostedZone for ${{self:custom.domainName}}"
        HostedZoneTags: ${{self:custom.resourceTags}}
        Name: ${{self:custom.domainName}}
  Outputs:
    HostedZoneRef:
      Description: 'Hosted Zone for domain'
      Value:
        Ref: HostedZone
      Export:
        Name:
          Fn::Join: ['',[ Ref: AWS::StackName,'-HostedZone']]
    NameServers:
      Description: 'Name servers for hosted zone'
      Value:
          Fn::Join: [', ', Fn::GetAtt: [HostedZone, NameServers]]


# commented as not receiving domain validation email.  create cert manually and do DNS validation as this isn't yet available via cloudformation
#    Certificate:
#          Type: AWS::CertificateManager::Certificate
#          Properties:
#             DomainName: "*.${{self:custom.domainName}}"
#             DomainValidationOptions:
#              - DomainName: ${{self:custom.domainName}}
#                ValidationDomain: ${{self:custom.domainName}}
#             SubjectAlternativeNames: ${{self:custom.alternateDomainName}}
#             Tags: ${{self:custom.resourceTags}}