service: template

custom:
  currentStage: ${{opt:stage, self:provider.stage}}
  domainName: crunch.ski
  resourceTags:
    -
      Key: "project"
      Value: "ski-analytics"
    -
      Key: "module"
      Value: "api"

provider:
  name: aws
  runtime: java8
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
  region: ca-central-1
  stage: staging
  stackName: ${{self:custom.currentStage}}-ski-analytics-<<name>>-stack
  iamRoleStatements:


package:
  artifact: build/distributions/<<name>.zip

functions:
resources: