    ## Common variables to pass into custom section of serverless.yml
    #always pass stage into scripts

    resourceTags:
      - Key: "project"
        Value: ${{self:custom.projectName}}
      - Key: "stage"
        Value: ${{opt:stage}}
      - Key: "module"
        Value: ${{self:service}}

    ## common variables
    projectName: ${{file(../../infra/stacks/global.tfvars.json):project_name}}
    domainName: ${{file(../../infra/stacks/global.tfvars.json):domain_name}}
    dataStack: ${{opt:stage}}-${{self:custom.projectName}}-data-var-stack

    ## tables
    userTable: ${{opt:stage}}-${{self:custom.projectName}}-userTable
    activityTable:  ${{opt:stage}}-${{self:custom.projectName}}-Activity

    ## buckets
    activityBucketName: ${{opt:stage}}-activity-${{self:custom.projectName}}
    rawActivityBucketName: ${{opt:stage}}-raw-activity-${{self:custom.projectName}}

    ##cognito
    userPoolArn: ${{cf:${{self:custom.dataStack}}.UserPoolArn${{opt:stage}}}}
    userPoolId: ${{cf:${{self:custom.dataStack}}.UserPoolId${{opt:stage}}}}
    userPoolClientId: ${{cf:${{self:custom.dataStack}}.UserPoolClientId${{opt:stage}}}}

    ## endpoints
    apiStack: ${{opt:stage}}-${{self:custom.projectName}}-api-var-stack
    apiSubDomain: ${{file(../../infra/stacks/api/dev.terraform.tfvars.json):api_sub_domain}}
    wsSubDomain: ${{file(../../infra/stacks/api/dev.terraform.tfvars.json):ws_sub_domain}}
    apiDomainName: ${{cf:${{self:custom.apiStack}}.APIEndpointName${{opt:stage}}}}
    apiDomainZone: ${{cf:${{self:custom.apiStack}}.APIEndpointZoneId${{opt:stage}}}}
    hostedZoneId: ${{cf:${{self:custom.apiStack}}.HostedZoneId${{opt:stage}}}}
    acmCertificateArn: ${{cf:${{self:custom.apiStack}}.AcmCertificateArn

