    runtime: java11
    variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
    region: ${{file(../../infra/stacks/global.tfvars.json):primary_region}}
    stackName: ${{opt:stage}}-${{self:custom.projectName}}-${{self:service}}
    stage: ${{opt:stage}}