## Stack provides two lambda layers:  utils (common code), and common (common dependencies)
## No dependencies on other stacks
service: common

provider:
  name: aws
  runtime: java8
  region: ${{file(../../infra/stacks/global.tfvars.json):primary_region}}
  stage: ${{opt:stage}}
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
  stackName: ${{opt:stage}}-${{self:custom.projectName}}-${{self:service}}

custom: ${{file(../../config/custom.yml)}}

layers:
  utils:
    name: ${{opt:stage}}-layer-utils
    description: domain classes for object model and utilities
    compatibleRuntimes:
      - java8
    retain: true
    package:
      include: 
        - src/main/java/ski/crunch/**
      artifact: build/distributions/${{self:custom.projectName}}-utils.zip
  common:
    name: ${{opt:stage}}-layer-${{self:service}}
    description: common dependencies for all services
    compatibleRuntimes:
      - java8
    retain: true
    package:
      include:
        - src/main/java/*
      artifact: build/distributions/${{self:custom.projectName}}-${{self:service}}.zip
