## This Stack depends on auth-stack
service: graphql

plugins:
  - serverless-appsync-plugin
provider:
  name: aws
  runtime: java11
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
  ## region hardcoded as appsync is not offered in ca-central-1 yet
  region: us-east-1
  stackName: ${{opt:stage}}-${{self:custom.projectName}}-${{self:service}}
  stage: ${{opt:stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${{self:custom.primaryRegion}}:*:table/${{self:custom.userTable}}"

custom:
  primaryRegion: ${{file(../../infra/envs/global.tfvars.json):primary_region}}
  resourceTags:
    - Key: "project"
      Value: ${{self:custom.projectName}}
    - Key: "stage"
      Value: ${{opt:stage}}
    - Key: "module"
      Value: ${{self:service}}

    ## common variables
  projectName: ${{file(../../infra/envs/global.tfvars.json):project_name}}
  domainName: ${{file(../../infra/envs/global.tfvars.json):domain_name}}
  dataStack: ${{opt:stage}}-${{self:custom.projectName}}-data-var-stack

    ## tables
  userTable: ${{opt:stage}}-${{self:custom.projectName}}-userTable
  activityTable:  ${{opt:stage}}-${{self:custom.projectName}}-Activity

    ## buckets
  activityBucketName: ${{opt:stage}}-activity-${{self:custom.projectName}}
  rawActivityBucketName: ${{opt:stage}}-raw-activity-${{self:custom.projectName}}

    ##cognito
  ## note that region is intentionally specified in cf output reference
  userPoolArn: ${{cf.${{self:custom.primaryRegion}}:${{self:custom.dataStack}}.UserPoolArn}}
  userTableDSName: ${{opt:stage}}_crunch_UserTable_DS
  authStackName: ${{opt:stage}}-${{self:custom.projectName}}-auth
  appSync:
    name: ${{opt:stage}}-appsync-api
    authenticationType: "AMAZON_COGNITO_USER_POOLS"
    userPoolConfig:
      userPoolId: ${{cf.${{self:custom.primaryRegion}}:${{self:custom.dataStack}}.UserPoolId}}
      awsRegion: ${{self:custom.primaryRegion}}
      defaultAction: "ALLOW"
    logConfig:
      loggingRoleArn: { Fn::GetAtt: [DynamoDBRole, Arn] } # Where AppSyncLoggingServiceRole is a role with CloudWatch Logs write access
      level: ALL # Logging Level: NONE | ERROR | ALL
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: ${{self:custom.userTableDSName}}
        type: Query
        field: getUser
        request: get-user-settings-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: addUser
        request: add-user-settings-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: saveHeight
        request: save-height-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: saveWeight
        request: save-weight-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: saveGender
        request: save-gender-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: saveHrZones
        request: save-hrzones-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: addTag
        request: add-tag-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: renameTag
        request: rename-tag-request-template.vtl
        response: generic-response-template.vtl
      - dataSource: ${{self:custom.userTableDSName}}
        type: Mutation
        field: deleteTag
        request: delete-tag-request-template.vtl
        response: generic-response-template.vtl
    schema: schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: ${{self:custom.userTableDSName}}
        description: "user settings table"
        config:
#          tableName: ${{self:custom.userTable}}
          tableName: ${{self:custom.userTable}}
          serviceRoleArn: { Fn::GetAtt: [DynamoDBRole, Arn] } # Where AppSyncDynamoDBServiceRole is an IAM role defined in Resources
          region: ${{self:custom.primaryRegion}}

resources:
  Resources:
    DynamoDBRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Principal:
                Service:
                  - appsync.amazonaws.com
        RoleName: ${{opt:stage}}-appsync-dynamodb-role
        ManagedPolicyArns:
          - Ref: AppSyncDynamoDBPolicy
          - Ref: AppSyncLoggingPolicy
      DependsOn:
        - AppSyncDynamoDBPolicy
        - AppSyncLoggingPolicy
    AppSyncLoggingPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: "Managed policy to allow appsync access to cloudwatch logs"
        Path: /appsync/
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:*
                - logs:*
              Resource: "*"

    AppSyncDynamoDBPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: "Managed policy to allow AWS AppSync to access the tables created by this template."
        Path: /appsync/
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
              Resource:  "arn:aws:dynamodb:${{self:custom.primaryRegion}}:*:table/${{self:custom.userTable}}"

