
service: authentication
tenant: aengus
app: ski-analytics

provider:
  name: aws
  runtime: java8
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
#  fallback to us-west as cognito not available in canada
  region: us-west-2
  stage: staging
  stackName: ${{self:custom.currentStage}}-ski-analytics-authentication-stack


custom:
  currentStage: ${{opt:stage, self:provider.stage}}

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          InviteMessageTemplate:
            #EmailMessage: ${{file(src/main/resources/verification_email.html)}}
            EmailMessage: "Hello there {username},  You're verification code is {####}"
            EmailSubject: "Welcome to Crunch.Ski!"
          UnusedAccountValidityDays: 365
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
            - email
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: false
          DeviceOnlyRememberedOnUserPrompt: false
#        EmailConfiguration: -> this is erroring out saying invalid email address :( set it manually in console
#          ReplyToEmailAddress: admin@ski-analytics.ca
#          SourceArn: arn:aws:ses:us-west-2:556823078430:identity/ski-analytics.ca
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            RequireUppercase: true
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: false
            Name: email
            Required: true
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: false
            Name: name
            StringAttributeConstraints:
              MinLength: 2
              MaxLength: 20
            Required: false
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: false
            Name: familyName
            StringAttributeConstraints:
              MinLength: 2
              MaxLength: 20
            Required: false
        UserPoolName: ${{self:custom.currentStage}}-crunch-ski-userpool
        UserPoolTags:
          project: ski-analytics
          module: auth
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
         ClientName: ${{self:custom.currentStage}}-crunch-ski-web
         ExplicitAuthFlows:
           - USER_PASSWORD_AUTH
         GenerateSecret: false
         UserPoolId:
           Ref: UserPool

#     IdentityPool:
#       Type: "AWS::Cognito::IdentityPool"
#       Properties:
#         IdentityPoolName: ${{self:custom.currentStage}}-crunch-ski-identitypool
#         AllowUnauthenticatedIdentities: false
#         CognitoIdentityProviders:
#           - ClientId:
#               Ref: UserPool
#             ProviderName:
#               Fn::GetAtt: [UserPool, ProviderName]
#             ServerSideTokenCheck: true


  Outputs:
    UserPoolArn:
      Value:
        Ref: UserPool
#      Export:
#        Name: UserPoolArn-${{self:custom.currentStage}}
      Export:
        Name:
          Fn::Join: ['',[ Ref: AWS::StackName,'-UserPoolArn']]
    UserPoolProviderName:
      Value:
        Fn::GetAtt: [UserPool, ProviderName]
    UserPoolProviderUrl:
      Value:
        Fn::GetAtt: [UserPool, ProviderURL]
    UserPoolClientId:
      Value:
        Ref: UserPoolClient
      Export:
        Name: UserPoolClient-${{self:custom.currentStage}}